environment:
  test_profile: default
  matrix:
    - java_version: 1.6.0
    - java_version: 1.7.0
    - java_version: 1.8.0
      test_profile: short
platform: x64
install:
  - ps: .\ci\appveyor.ps1
build_script:
  - "set \"JAVA_HOME=%JAVA_8_HOME%\" && mvn install -DskipTests=true -B -V"
test_script:
  - "set \"JAVA_HOME=%JAVA_PLATFORM_HOME%\" && mvn -B -D\"ccm.java.home\"=\"%JAVA_8_HOME%\" -D\"ccm.maxNumberOfNodes\"=1 -D\"cassandra.version\"=%cassandra_version% verify -P %test_profile%"
on_finish:
  - ps: .\ci\uploadtests.ps1
cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ccm\repository
  - C:\Users\appveyor\deps -> .\ci\appveyor.ps1
